In [3]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [5]:
import numpy

ar = array[1, 2, 3, 4, 5]

print(ar)

NameError: name 'array' is not defined

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [7]:
import numpy as np
print(np.__version__)

1.18.5


In [8]:
import numpy as np
arr  = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
import numpy as np
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [10]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [11]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [13]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [16]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [17]:
import numpy as np
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
import numpy as np
arr = n